/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class AppTest {
     @Test
     public void testAppHasAGreeting() {
        //App.main(new String[0]);
    } 
}
 